Fix UI issues on view
AY2324S2-CS2113-W13-2/tp pull request #103
Opened 2024-03-29 14:17 UTC by Mahesh1772

2024-03-29 14:25 UTC, Aak242 reviewed
LGTM!

2024-03-29 14:25 UTC, Aak242 commented on src/main/java/ui/UiRenderer.java
> +    private static final String EMPTY_TASK_DISPLAY_FORMAT = VERTICAL_DIVIDER + " ".repeat(SPACE_COUNT + 2);
We might want to consider using final variables that store this constant value of 2 in order to better explain what it does like "STANDARD_TWO_SPACE_OFFSET"

2024-03-29 15:26 UTC, kyhjonathan commented on src/main/java/ui/UiRenderer.java
> +    private static final String ENTRY_FORMAT = VERTICAL_DIVIDER + " %-" + SPACE_COUNT + "s ";
LGTM!

2024-03-29 15:26 UTC, kyhjonathan commented on src/test/java/ui/UiRendererTest.java
> +    private static final String TASK_DISPLAY_FORMAT = VERTICAL_DIVIDER + " %-" + SPACE_COUNT + "." + SPACE_COUNT + "s ";
Good job fixing the UI issues!

2024-03-30 02:59 UTC, NicholasTanYY requested changes
Good attempt at trying to fix the UI issues, but I think it would be better to fix the way MonthView is being rendered instead.

2024-03-30 02:59 UTC, NicholasTanYY commented on src/main/java/ui/UiRenderer.java
> +    private static final String ENTRY_FORMAT = VERTICAL_DIVIDER + " %-" + SPACE_COUNT + "s ";
As discussed, let's not introduce random spacings into the formatting! Need to change the formatting for the spacings within MonthView to follow this instead.

2024-04-02 09:47 UTC, NicholasTanYY reviewed
Overall LGTM, but we need to make some implementations to fix the month view in a later iteration.

2024-04-02 09:47 UTC, NicholasTanYY commented on src/main/java/time/MonthView.java
>      }
Good use of the string constants here instead of the magic numbers!

2024-04-02 09:47 UTC, NicholasTanYY commented on src/main/java/time/MonthView.java
>      }
good implementation!

2024-04-02 09:47 UTC, NicholasTanYY commented on src/main/java/time/MonthView.java
> +        if (currentDate.getMonth().equals(YearMonth.from(startOfMonth).getMonth())) {
this might be more readable if we split them into booleans!

2024-04-02 09:50 UTC, merged