Some DG changes
AY2324S2-CS2113-W13-2/tp pull request #160
Opened 2024-04-14 14:10 UTC by Mahesh1772

2024-04-14 17:09 UTC, NicholasTanYY requested changes
Overall, great job on including UML diagrams! Could you make some of the minor modification suggested before merging the changes?

2024-04-14 17:09 UTC, NicholasTanYY commented on docs/DeveloperGuide.md
> +Sure, here's the updated section of the Developer Guide for the `CommandHandler` class:
Might want to remove this line !

2024-04-14 17:09 UTC, NicholasTanYY commented on docs/DeveloperGuide.md
> +11. **handleQuitCommand()**: Exits the application.
Great job on detailing the commands in the command parser in to the DG!

2024-04-14 17:09 UTC, NicholasTanYY commented on docs/diagrams/class/CommandParser.puml
> +@enduml
This UML diagram looks good!

2024-04-14 17:09 UTC, NicholasTanYY commented on docs/diagrams/class/Time.puml
> +}
Great job on tackling the inheritance between classes!

2024-04-14 17:09 UTC, NicholasTanYY commented on docs/diagrams/sequence/PrintMonthViewSequenceDiagram.puml
> +
Great job on this sequence diagram! However, do note that the sequence headings should have the colon within them.

2024-04-14 17:09 UTC, NicholasTanYY commented on docs/team/mahesh1772.md
> +My involvement in this project has been a profound learning experience, sharpening my skills in UI/UX design, command-line interfaces, and software architecture. The challenges I faced pushed me to i
What an insightful reflection! It was nice to have you on the team Mahesh!

2024-04-15 01:58 UTC, clarencepohh requested changes
Please take note of the UML notation errors and missing attributes

2024-04-15 01:58 UTC, clarencepohh commented on docs/DeveloperGuide.md
> +![Time.png](images%2Fclass%2FTime.png)
Image path likely will not be found causing the images to not load. Possibly rectify with slashes `/` instead of `%2F`

2024-04-15 01:58 UTC, clarencepohh commented on docs/DeveloperGuide.md
> +Sure, here's the updated version of the "View Switching in Main" section that fits with the `handleMonthCommand()` and `handleWeekCommand()` methods:
Should this be here?

2024-04-15 01:58 UTC, clarencepohh commented on docs/DeveloperGuide.md
> +![CommandParser.png](images%2Fclass%2FCommandParser.png)
Similar comment as above

2024-04-15 01:58 UTC, clarencepohh commented on docs/UserGuide.md
> +Format: `add, <day number>, <taskType>, <taskDescription>`
Thanks for changing this to make it clearer to the reader!

2024-04-15 01:58 UTC, clarencepohh commented on docs/UserGuide.md
> +Your Todo Task is now added to your calendar on the selected day (of whichever week/month you are viewing)!
Thanks for fixing the typo!

2024-04-15 01:58 UTC, clarencepohh commented on docs/diagrams/class/CommandParser.puml
> +    - printHelp(): void
This command appears to be static. Should probably include the {static} field

2024-04-15 01:58 UTC, clarencepohh commented on docs/diagrams/class/CommandParser.puml
> +class StringParser {
Is the class missing the attribute `private static final DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy")`?

2024-04-15 01:58 UTC, clarencepohh commented on docs/diagrams/class/Time.puml
> +abstract class View {
`protected LocalDate startOfView`
`protected final DateTimeFormatter dateFormatter`
Are these attributes missing?

2024-04-15 01:58 UTC, clarencepohh commented on docs/diagrams/class/Time.puml
> +abstract class View {
Sorry not missing, the visibility should be protected and not private. Use `#` instead of `-` to show protected variables

2024-04-15 01:58 UTC, clarencepohh commented on docs/diagrams/class/Time.puml
> +class MonthView extends View {
`private static final Logger logger = Logger.getLogger(Logger.GLOBAL_LOGGER_NAME)`
`private static final int NUMBER_OF_DAYS_IN_WEEK = 7`
`private final UiRenderer uiRenderer`
Are these attributes missing?

2024-04-15 01:58 UTC, clarencepohh commented on docs/team/mahesh1772.md
Very detailed explanation on your contributions! Great job Mahesh!

2024-04-15 11:54 UTC, kyhjonathan commented on docs/DeveloperGuide.md
> +### printMonthView Method
Good job in updating the printMonthView method!

2024-04-15 11:54 UTC, kyhjonathan commented on docs/DeveloperGuide.md
> +This `handleWeekCommand()` method sets the `inMonthView` flag to `false`, indicating that the week view should be displayed.
LGTM!

2024-04-15 11:54 UTC, kyhjonathan commented on docs/DeveloperGuide.md
> +```java
Perhaps this could be explained with a screenshot?

2024-04-15 11:57 UTC, merged